### ISSUE TITLE
Error in load_cylind when given a list of lat, lon points 

### ISSUE THREAD

**Issue by am-thyst** [miniufo/xvortices#2]
Thanks for making this package! It's really useful.

I'm having a problem with `load_cylind` when using a list of latitude and longitude values (for a moving TC). 

I can replicate the error by using the function source code:

```python
import numpy as np
import xarray as xr
from numpy import deg2rad, sin, cos, arcsin, arccos, arctan2, hypot

azimNum, radiNum, radMax = 72, 60, 300/111
olon = [289.1753898531895, 289.152032972555]
olat = [21.880864009020737, 22.020510476257623]

azim = xr.DataArray(np.linspace(0, 360-360/azimNum, azimNum),
                        dims='azim',
                        coords={'azim':np.linspace(0, 360-360/azimNum, azimNum)})
radi = xr.DataArray(np.linspace(0, radMax, radiNum),
                        dims='radi',
                        coords={'radi':np.linspace(0, radMax, radiNum)})

olon_r = deg2rad(olon)
olat_r = deg2rad(olat)
azim_r = deg2rad(azim)
radi_r = deg2rad(radi)

lats_r = arcsin(sin(olat_r)*cos(radi_r) + cos(olat_r)*sin(radi_r)*cos(azim_r))
```

Error:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/home02/eeajo/miniconda3/envs/py36/lib/python3.8/site-packages/xarray/core/arithmetic.py", line 70, in __array_ufunc__
    return apply_ufunc(
  File "/home/home02/eeajo/miniconda3/envs/py36/lib/python3.8/site-packages/xarray/core/computation.py", line 1128, in apply_ufunc
    return apply_dataarray_vfunc(
  File "/home/home02/eeajo/miniconda3/envs/py36/lib/python3.8/site-packages/xarray/core/computation.py", line 271, in apply_dataarray_vfunc
    result_var = func(*data_vars)
  File "/home/home02/eeajo/miniconda3/envs/py36/lib/python3.8/site-packages/xarray/core/computation.py", line 724, in apply_variable_ufunc
    result_data = func(*input_data)
ValueError: operands could not be broadcast together with shapes (2,) (60,)
```

I understand the error - it doesn't make sense to do a mathematical operation with those array shapes. However, I can't understand how this is different to your notebook example. I would expect you might need to do a loop through the times but that doesn't seem to be the case in the example.

How would this be solved?

**Comment by miniufo** [comment]
Hi, sorry about this.  I take a look at the code and the doc string may be misleading.  To make sure your codes can take the advantage of xarray, I suggest to write olon/olat as:
```python
olon = xr.DataArray([289.1753898531895, 289.152032972555], dims='time',
                 coords={'time':np.array([0, 1])})
olat = xr.DataArray([21.880864009020737, 22.020510476257623], dims='time',
                 coords={'time':np.array([0, 1])})
```

Note that the time coordinate should be exactly the same as those in your dataset.

**Comment by am-thyst** [comment]
Solved, thank you very much! 

Yes, I think the confusion came from this line: `(list of) float, numpy.array, or xarray.DataArray`, which implies that you can just use a list of floats.
